name: Build Release

on:
  workflow_dispatch:

jobs:
  build_release:

    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v5
      with:
          fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: ./global.json
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Get Version
      uses: nivaes/version-pack@v2
      id: version_pack
      with:
        package-flow: preview

    - name: Restore Dependencies
      run: |
          dotnet restore

    - name: Build
      run: dotnet build --configuration Release -p:Version=${{ steps.version_pack.outputs.version-pack }} --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --no-restore --no-build

    - name: Pack
      if: github.event_name == 'push' || (github.event_name != 'pull_request')
      run: dotnet pack --configuration Release --no-build --verbosity normal --output ./Artifacts/ -p:Version=${{ steps.version_pack.outputs.version-pack }} --no-restore

    # - name: Create Release
    #   if: github.event_name == 'push' || (github.event_name != 'pull_request')
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: release/v${{ steps.pack.outputs.version }}
    #     release_name: Release Version ${{ steps.version_pack.outputs.version }}
    #     body: |
    #       Automatic Release ${{ steps.version_pack.outputs.version }}   
    #       - Release automatically generated.
    #     draft: true
    #     prerelease: false

    # - name: Upload Release Asset
    #   uses: nivaes/upload-release-assets@master
    #   env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #      upload_url: ${{ steps.create_release.outputs.upload_url }}
    #      targets: ./Artifacts/*.{nupkg,snupkg}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version_pack.outputs.version-release }}
        name: "Release ${{ steps.version_pack.outputs.version-number }}"
        body: |
          Automatic release generated from GitHub Actions.
        draft: true
        prerelease: false
        files: |
          ./Artifacts/*.{nupkg,snupkg}
